# -*- coding: utf-8 -*-
"""speechtotext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBc5daSGiY16akqJCN9W6GjfKShYh9Hw

## Instal library speech recogniner
"""

pip install speechrecognition

"""## Import Librarynya ya"""

import speech_recognition as sr

r = sr.Recognizer()
r

"""## Import Audionya ya dari Drive saja"""

from google.colab import drive
drive.mount('/content/drive')

from IPython.lib.display import Audio
suaranya = sr.AudioFile('/content/drive/MyDrive/Colab Notebooks/Speechtotext/ngomong.wav')
with suaranya as source:
  Audio = r.record(source)

type(Audio)

"""##  Konversi audio ke Text"""

text = r.recognize_google(Audio, language="id-ID")
text